1699298823940	Sync.LogManager	DEBUG	Flushing file log
1699298823951	Sync.LogManager	DEBUG	Log cleanup threshold time: 1698434823951
1699298823968	Sync.LogManager	DEBUG	Done deleting files.
1699298826204	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1699298826204	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1699298826205	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1699298826206	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1699298827691	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1699298827691	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1699298827695	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1699298827696	Sync.Service	DEBUG	User-Agent: Firefox/119.0 (Linux x86_64) FxSync/1.121.0.20231023160744.desktop
1699298827696	Sync.Service	INFO	Starting sync at 2023-11-06 13:27:07 in browser session mDCa76O0maZ8
1699298827696	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1699298827698	Sync.Status	INFO	Resetting Status.
1699298827698	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1699298827698	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1699298828172	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/147255507/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1699298828172	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1699298828172	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1699298828172	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1699298828172	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1699298828174	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
