1699242233887	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1699245819676	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1699245828813	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1699245830663	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1699245831968	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1699245833969	Sync.Service	DEBUG	User-Agent: Firefox/117.0 (Linux x86_64) FxSync/1.119.0.20230828231221.desktop
1699245833969	Sync.Service	INFO	Starting sync at 2023-11-05 22:43:53 in browser session -8jiSp5-XV1m
1699245833969	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1699245833972	Sync.Status	INFO	Resetting Status.
1699245833972	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1699245833973	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1699245833973	FirefoxAccounts	DEBUG	getOAuthToken enter
1699245833973	FirefoxAccounts	TRACE	getCachedToken returning cached token
1699245833973	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1699245833973	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1699245833974	Sync.SyncAuthManager	INFO	Getting sync key
1699245833974	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1699245833974	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1699245833974	FirefoxAccounts	DEBUG	getOAuthToken enter
1699245833974	FirefoxAccounts	TRACE	getCachedToken returning cached token
1699245833974	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1699245833975	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1699245833975	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1699245833980	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1699245833980	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 479\"  data: no]"}
1699245833981	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1699245833981	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1699245833982	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1699245833982	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1699245833982	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1699245833983	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1699245833988	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/147756523/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1699245833988	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1699245833988	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1699245833989	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1699245833989	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1699245833990	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1699245833994	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
