1695111956700	Sync.LogManager	DEBUG	Flushing file log
1695111956701	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1695111956701	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 479\"  data: no]"}
1695111956703	Sync.LogManager	DEBUG	Log cleanup threshold time: 1694247956703
1695111956706	Sync.LogManager	DEBUG	Done deleting files.
1695115557511	Sync.Service	DEBUG	User-Agent: Firefox/117.0 (Linux x86_64) FxSync/1.119.0.20230828231221.desktop
1695115557511	Sync.Service	INFO	Starting sync at 2023-09-19 03:25:57 in browser session vZDuxHVMJ0sK
1695115557511	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1695115557516	Sync.Status	INFO	Resetting Status.
1695115557516	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1695115557516	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1695115557516	FirefoxAccounts	DEBUG	getOAuthToken enter
1695115557517	FirefoxAccounts	TRACE	getCachedToken returning cached token
1695115557517	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1695115557517	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1695115557518	Sync.SyncAuthManager	INFO	Getting sync key
1695115557518	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1695115557518	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1695115557519	FirefoxAccounts	DEBUG	getOAuthToken enter
1695115557519	FirefoxAccounts	TRACE	getCachedToken returning cached token
1695115557519	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1695115557519	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1695115557519	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1695115557526	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1695115557526	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 479\"  data: no]"}
1695115557528	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1695115557529	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1695115557529	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1695115557529	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1695115557529	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1695115557531	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1695115557537	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/147255507/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1695115557537	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1695115557537	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1695115557538	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1695115557538	Sync.SyncScheduler	DEBUG	Sync error count has exceeded 3; enforcing backoff.
1695115557538	Sync.SyncScheduler	DEBUG	Starting client-initiated backoff. Next sync in 2888034 ms.
1695115557538	Sync.SyncScheduler	DEBUG	Next sync in 2888034 ms. (why=client-backoff-schedule)
1695115557539	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1695115557546	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
