1695111356670	Sync.LogManager	DEBUG	Flushing file log
1695111356675	Sync.LogManager	DEBUG	Log cleanup threshold time: 1694247356675
1695111356681	Sync.LogManager	DEBUG	Done deleting files.
1695111956687	Sync.Service	DEBUG	User-Agent: Firefox/117.0 (Linux x86_64) FxSync/1.119.0.20230828231221.desktop
1695111956688	Sync.Service	INFO	Starting sync at 2023-09-19 02:25:56 in browser session vZDuxHVMJ0sK
1695111956688	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1695111956692	Sync.Status	INFO	Resetting Status.
1695111956692	Sync.Status	DEBUG	Status.service: error.sync.failed => success.status_ok
1695111956692	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1695111956692	FirefoxAccounts	DEBUG	getOAuthToken enter
1695111956693	FirefoxAccounts	TRACE	getCachedToken returning cached token
1695111956693	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1695111956693	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1695111956697	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/147255507/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1695111956697	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1695111956698	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1695111956698	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1695111956698	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1695111956700	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
