1693657421766	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1693657422683	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1693657503507	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1693657505099	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1693657505099	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1693657505102	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1693657505104	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1693657514507	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1693657514507	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1693657514512	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1693657514513	Sync.Service	DEBUG	User-Agent: Firefox/117.0 (Linux x86_64) FxSync/1.119.0.20230828231221.desktop
1693657514513	Sync.Service	INFO	Starting sync at 2023-09-02 06:25:14 in browser session n4mAfpq7IG5H
1693657514513	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1693657514515	Sync.Status	INFO	Resetting Status.
1693657514515	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1693657514516	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1693657514516	FirefoxAccounts	DEBUG	getOAuthToken enter
1693657514516	FirefoxAccounts	TRACE	getCachedToken returning cached token
1693657514516	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1693657514516	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1693657514544	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1693657514544	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 479\"  data: no]"}
1693657514547	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/147255507/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1693657514547	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1693657514548	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1693657514548	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1693657514548	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1693657514550	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
