1695347943679	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1695347945391	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1695348237021	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1695348238577	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1695348238577	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1695348238581	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1695348238583	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1695348240673	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1695348241779	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1695348241779	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1695348241784	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1695348241785	Sync.Service	DEBUG	User-Agent: Firefox/117.0 (Linux x86_64) FxSync/1.119.0.20230828231221.desktop
1695348241785	Sync.Service	INFO	Starting sync at 2023-09-21 20:04:01 in browser session i4ZHtb2Smtg0
1695348241785	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1695348241787	Sync.Status	INFO	Resetting Status.
1695348241787	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1695348241787	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1695348241787	FirefoxAccounts	DEBUG	getOAuthToken enter
1695348241788	FirefoxAccounts	TRACE	getCachedToken returning cached token
1695348241788	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1695348241788	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1695348241799	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1695348241800	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 479\"  data: no]"}
1695348241803	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/147255507/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1695348241803	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1695348241803	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1695348241803	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1695348241804	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1695348241806	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
